'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Otority
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.Otority", GetType(Otority).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Public Shared ReadOnly Property DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add?.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_ISADD() As String
            Get
                Return ResourceManager.GetString("DETAIL_ISADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete?.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_ISDELETE() As String
            Get
                Return ResourceManager.GetString("DETAIL_ISDELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print?.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_ISPRINT() As String
            Get
                Return ResourceManager.GetString("DETAIL_ISPRINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update?.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_ISUPDATE() As String
            Get
                Return ResourceManager.GetString("DETAIL_ISUPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View?.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_ISVIEW() As String
            Get
                Return ResourceManager.GetString("DETAIL_ISVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_MENUNAME() As String
            Get
                Return ResourceManager.GetString("DETAIL_MENUNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modul.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_MODUL() As String
            Get
                Return ResourceManager.GetString("DETAIL_MODUL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active?.
        '''</summary>
        Public Shared ReadOnly Property ISACTIVE() As String
            Get
                Return ResourceManager.GetString("ISACTIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Public Shared ReadOnly Property KDOTORITY() As String
            Get
                Return ResourceManager.GetString("KDOTORITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("TAB_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detail Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_DETAIL() As String
            Get
                Return ResourceManager.GetString("TAB_DETAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Otority.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
