'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Statement
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.Statement", GetType(Statement).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup not success! Please consult your administrator!.
        '''</summary>
        Public Shared ReadOnly Property BackupFail() As String
            Get
                Return ResourceManager.GetString("BackupFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup success!.
        '''</summary>
        Public Shared ReadOnly Property BackupSuccess() As String
            Get
                Return ResourceManager.GetString("BackupSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There must be a minimum of one listed as default!.
        '''</summary>
        Public Shared ReadOnly Property CheckDefault() As String
            Get
                Return ResourceManager.GetString("CheckDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database is not active! Please consult your administrator!.
        '''</summary>
        Public Shared ReadOnly Property DatabaseInactive() As String
            Get
                Return ResourceManager.GetString("DatabaseInactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete not success! Please consult your administrator!.
        '''</summary>
        Public Shared ReadOnly Property DeleteFail() As String
            Get
                Return ResourceManager.GetString("DeleteFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete this transaction?.
        '''</summary>
        Public Shared ReadOnly Property DeleteQuestion() As String
            Get
                Return ResourceManager.GetString("DeleteQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete success!.
        '''</summary>
        Public Shared ReadOnly Property DeleteSuccess() As String
            Get
                Return ResourceManager.GetString("DeleteSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detail required!.
        '''</summary>
        Public Shared ReadOnly Property ErrorDetail() As String
            Get
                Return ResourceManager.GetString("ErrorDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debit and credit must equal!.
        '''</summary>
        Public Shared ReadOnly Property ErrorEqual() As String
            Get
                Return ResourceManager.GetString("ErrorEqual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Repeat same password!.
        '''</summary>
        Public Shared ReadOnly Property ErrorPasswordRepeat() As String
            Get
                Return ResourceManager.GetString("ErrorPasswordRepeat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is already registered!.
        '''</summary>
        Public Shared ReadOnly Property ErrorRegistered() As String
            Get
                Return ResourceManager.GetString("ErrorRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is required!.
        '''</summary>
        Public Shared ReadOnly Property ErrorRequired() As String
            Get
                Return ResourceManager.GetString("ErrorRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimum 1 unit with rate : 1.
        '''</summary>
        Public Shared ReadOnly Property ErrorRequiredRate() As String
            Get
                Return ResourceManager.GetString("ErrorRequiredRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error : .
        '''</summary>
        Public Shared ReadOnly Property ErrorStatement() As String
            Get
                Return ResourceManager.GetString("ErrorStatement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit is not registered on this item, please contact your administrator!.
        '''</summary>
        Public Shared ReadOnly Property ErrorUOM() As String
            Get
                Return ResourceManager.GetString("ErrorUOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username or Password is not correct! Please consult your administrator!.
        '''</summary>
        Public Shared ReadOnly Property ErrorUserPassword() As String
            Get
                Return ResourceManager.GetString("ErrorUserPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to exit application?.
        '''</summary>
        Public Shared ReadOnly Property ExitApplication() As String
            Get
                Return ResourceManager.GetString("ExitApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to data..
        '''</summary>
        Public Shared ReadOnly Property ExportData() As String
            Get
                Return ResourceManager.GetString("ExportData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saving to database.
        '''</summary>
        Public Shared ReadOnly Property ExportDone() As String
            Get
                Return ResourceManager.GetString("ExportDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Processing.
        '''</summary>
        Public Shared ReadOnly Property ExportProcessing() As String
            Get
                Return ResourceManager.GetString("ExportProcessing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export?.
        '''</summary>
        Public Shared ReadOnly Property ExportQuestion() As String
            Get
                Return ResourceManager.GetString("ExportQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Done!.
        '''</summary>
        Public Shared ReadOnly Property ExportSuccess() As String
            Get
                Return ResourceManager.GetString("ExportSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore not success! Please consult your administrator!.
        '''</summary>
        Public Shared ReadOnly Property RestoreFail() As String
            Get
                Return ResourceManager.GetString("RestoreFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore success!.
        '''</summary>
        Public Shared ReadOnly Property RestoreSuccess() As String
            Get
                Return ResourceManager.GetString("RestoreSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save configuration? (Application will be shut down!).
        '''</summary>
        Public Shared ReadOnly Property SaveDatabase() As String
            Get
                Return ResourceManager.GetString("SaveDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save not success! Please consult your administrator!.
        '''</summary>
        Public Shared ReadOnly Property SaveFail() As String
            Get
                Return ResourceManager.GetString("SaveFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save this transaction?.
        '''</summary>
        Public Shared ReadOnly Property SaveQuestion() As String
            Get
                Return ResourceManager.GetString("SaveQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save success!.
        '''</summary>
        Public Shared ReadOnly Property SaveSuccess() As String
            Get
                Return ResourceManager.GetString("SaveSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security is not installed, please contact your administrator!.
        '''</summary>
        Public Shared ReadOnly Property SecurityNotInstalled() As String
            Get
                Return ResourceManager.GetString("SecurityNotInstalled", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
