'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="BJG_INDIGO")>  _
Partial Public Class dcOnlineDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertNewsLetterSubscription(instance As NewsLetterSubscription)
    End Sub
  Partial Private Sub UpdateNewsLetterSubscription(instance As NewsLetterSubscription)
    End Sub
  Partial Private Sub DeleteNewsLetterSubscription(instance As NewsLetterSubscription)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.UI.WIN.MAIN.My.MySettings.Default.BJG_INDIGOConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property NewsLetterSubscriptions() As System.Data.Linq.Table(Of NewsLetterSubscription)
		Get
			Return Me.GetTable(Of NewsLetterSubscription)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.NewsLetterSubscription")>  _
Partial Public Class NewsLetterSubscription
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Id As Integer
	
	Private _NewsLetterSubscriptionGuid As System.Guid
	
	Private _Email As String
	
	Private _Active As Boolean
	
	Private _StoreId As Integer
	
	Private _CreatedOnUtc As Date
	
	Private _USED As Integer
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnIdChanged()
    End Sub
    Partial Private Sub OnNewsLetterSubscriptionGuidChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnNewsLetterSubscriptionGuidChanged()
    End Sub
    Partial Private Sub OnEmailChanging(value As String)
    End Sub
    Partial Private Sub OnEmailChanged()
    End Sub
    Partial Private Sub OnActiveChanging(value As Boolean)
    End Sub
    Partial Private Sub OnActiveChanged()
    End Sub
    Partial Private Sub OnStoreIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnStoreIdChanged()
    End Sub
    Partial Private Sub OnCreatedOnUtcChanging(value As Date)
    End Sub
    Partial Private Sub OnCreatedOnUtcChanged()
    End Sub
    Partial Private Sub OnUSEDChanging(value As Integer)
    End Sub
    Partial Private Sub OnUSEDChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property Id() As Integer
		Get
			Return Me._Id
		End Get
		Set
			If ((Me._Id = value)  _
						= false) Then
				Me.OnIdChanging(value)
				Me.SendPropertyChanging
				Me._Id = value
				Me.SendPropertyChanged("Id")
				Me.OnIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NewsLetterSubscriptionGuid", DbType:="UniqueIdentifier NOT NULL")>  _
	Public Property NewsLetterSubscriptionGuid() As System.Guid
		Get
			Return Me._NewsLetterSubscriptionGuid
		End Get
		Set
			If ((Me._NewsLetterSubscriptionGuid = value)  _
						= false) Then
				Me.OnNewsLetterSubscriptionGuidChanging(value)
				Me.SendPropertyChanging
				Me._NewsLetterSubscriptionGuid = value
				Me.SendPropertyChanged("NewsLetterSubscriptionGuid")
				Me.OnNewsLetterSubscriptionGuidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="NVarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me.OnEmailChanging(value)
				Me.SendPropertyChanging
				Me._Email = value
				Me.SendPropertyChanged("Email")
				Me.OnEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Active", DbType:="Bit NOT NULL")>  _
	Public Property Active() As Boolean
		Get
			Return Me._Active
		End Get
		Set
			If ((Me._Active = value)  _
						= false) Then
				Me.OnActiveChanging(value)
				Me.SendPropertyChanging
				Me._Active = value
				Me.SendPropertyChanged("Active")
				Me.OnActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StoreId", DbType:="Int NOT NULL")>  _
	Public Property StoreId() As Integer
		Get
			Return Me._StoreId
		End Get
		Set
			If ((Me._StoreId = value)  _
						= false) Then
				Me.OnStoreIdChanging(value)
				Me.SendPropertyChanging
				Me._StoreId = value
				Me.SendPropertyChanged("StoreId")
				Me.OnStoreIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedOnUtc", DbType:="DateTime NOT NULL")>  _
	Public Property CreatedOnUtc() As Date
		Get
			Return Me._CreatedOnUtc
		End Get
		Set
			If ((Me._CreatedOnUtc = value)  _
						= false) Then
				Me.OnCreatedOnUtcChanging(value)
				Me.SendPropertyChanging
				Me._CreatedOnUtc = value
				Me.SendPropertyChanged("CreatedOnUtc")
				Me.OnCreatedOnUtcChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USED", DbType:="Int NOT NULL")>  _
	Public Property USED() As Integer
		Get
			Return Me._USED
		End Get
		Set
			If ((Me._USED = value)  _
						= false) Then
				Me.OnUSEDChanging(value)
				Me.SendPropertyChanging
				Me._USED = value
				Me.SendPropertyChanged("USED")
				Me.OnUSEDChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
