'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class DiagnosaMaster
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.DiagnosaMaster", GetType(DiagnosaMaster).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit Date.
        '''</summary>
        Public Shared ReadOnly Property DATE_KELUAR() As String
            Get
                Return ResourceManager.GetString("DATE_KELUAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Control Date.
        '''</summary>
        Public Shared ReadOnly Property DATE_KONTROL() As String
            Get
                Return ResourceManager.GetString("DATE_KONTROL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entry Date.
        '''</summary>
        Public Shared ReadOnly Property DATE_MASUK() As String
            Get
                Return ResourceManager.GetString("DATE_MASUK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guarantee.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN() As String
            Get
                Return ResourceManager.GetString("JAMINAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How to Exit.
        '''</summary>
        Public Shared ReadOnly Property KDCARAKELUAR() As String
            Get
                Return ResourceManager.GetString("KDCARAKELUAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poly/Room.
        '''</summary>
        Public Shared ReadOnly Property KDDEPARTMENT() As String
            Get
                Return ResourceManager.GetString("KDDEPARTMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checks field.
        '''</summary>
        Public Shared ReadOnly Property KDDEPARTMENT_KONTROL() As String
            Get
                Return ResourceManager.GetString("KDDEPARTMENT_KONTROL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primary Diagnosis.
        '''</summary>
        Public Shared ReadOnly Property KDDIAGNOSA1() As String
            Get
                Return ResourceManager.GetString("KDDIAGNOSA1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondary Diagnosis - 1.
        '''</summary>
        Public Shared ReadOnly Property KDDIAGNOSA2() As String
            Get
                Return ResourceManager.GetString("KDDIAGNOSA2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondary Diagnosis - 2.
        '''</summary>
        Public Shared ReadOnly Property KDDIAGNOSA3() As String
            Get
                Return ResourceManager.GetString("KDDIAGNOSA3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondary Diagnosis - 3.
        '''</summary>
        Public Shared ReadOnly Property KDDIAGNOSA4() As String
            Get
                Return ResourceManager.GetString("KDDIAGNOSA4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondary Diagnosis - 4.
        '''</summary>
        Public Shared ReadOnly Property KDDIAGNOSA5() As String
            Get
                Return ResourceManager.GetString("KDDIAGNOSA5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondary Diagnosis - 5.
        '''</summary>
        Public Shared ReadOnly Property KDDIAGNOSA6() As String
            Get
                Return ResourceManager.GetString("KDDIAGNOSA6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DPJP Doctor.
        '''</summary>
        Public Shared ReadOnly Property KDDOCTOR() As String
            Get
                Return ResourceManager.GetString("KDDOCTOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Public Shared ReadOnly Property KDKDDIAGNOSAMASTER() As String
            Get
                Return ResourceManager.GetString("KDKDDIAGNOSAMASTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rawat Class.
        '''</summary>
        Public Shared ReadOnly Property KDKELASRAWAT() As String
            Get
                Return ResourceManager.GetString("KDKELASRAWAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home Conditions.
        '''</summary>
        Public Shared ReadOnly Property KDPASCAPULANG() As String
            Get
                Return ResourceManager.GetString("KDPASCAPULANG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Registration.
        '''</summary>
        Public Shared ReadOnly Property KDPENDAFTARAN() As String
            Get
                Return ResourceManager.GetString("KDPENDAFTARAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Referred To.
        '''</summary>
        Public Shared ReadOnly Property KDPPK() As String
            Get
                Return ResourceManager.GetString("KDPPK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedure - 1.
        '''</summary>
        Public Shared ReadOnly Property KDPROCEDURE1() As String
            Get
                Return ResourceManager.GetString("KDPROCEDURE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedure - 2.
        '''</summary>
        Public Shared ReadOnly Property KDPROCEDURE2() As String
            Get
                Return ResourceManager.GetString("KDPROCEDURE2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedure - 3.
        '''</summary>
        Public Shared ReadOnly Property KDPROCEDURE3() As String
            Get
                Return ResourceManager.GetString("KDPROCEDURE3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedure - 4.
        '''</summary>
        Public Shared ReadOnly Property KDPROCEDURE4() As String
            Get
                Return ResourceManager.GetString("KDPROCEDURE4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedure - 5.
        '''</summary>
        Public Shared ReadOnly Property KDPROCEDURE5() As String
            Get
                Return ResourceManager.GetString("KDPROCEDURE5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedure - 6.
        '''</summary>
        Public Shared ReadOnly Property KDPROCEDURE6() As String
            Get
                Return ResourceManager.GetString("KDPROCEDURE6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specialist.
        '''</summary>
        Public Shared ReadOnly Property KDSPESIALISTIK() As String
            Get
                Return ResourceManager.GetString("KDSPESIALISTIK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. SEP.
        '''</summary>
        Public Shared ReadOnly Property NOMORSEP() As String
            Get
                Return ResourceManager.GetString("NOMORSEP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Follow-up.
        '''</summary>
        Public Shared ReadOnly Property TINDAKLANJUT() As String
            Get
                Return ResourceManager.GetString("TINDAKLANJUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnosa Master.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnosa Master Report.
        '''</summary>
        Public Shared ReadOnly Property TITLE_REPORT() As String
            Get
                Return ResourceManager.GetString("TITLE_REPORT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
