'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Pendaftaran
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.Pendaftaran", GetType(Pendaftaran).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference Origin.
        '''</summary>
        Public Shared ReadOnly Property ASALRUJUKAN() As String
            Get
                Return ResourceManager.GetString("ASALRUJUKAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note.
        '''</summary>
        Public Shared ReadOnly Property CATATAN() As String
            Get
                Return ResourceManager.GetString("CATATAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kind of service.
        '''</summary>
        Public Shared ReadOnly Property CATEGORY() As String
            Get
                Return ResourceManager.GetString("CATEGORY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of reference.
        '''</summary>
        Public Shared ReadOnly Property DATE_RUJUKAN() As String
            Get
                Return ResourceManager.GetString("DATE_RUJUKAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COB?.
        '''</summary>
        Public Shared ReadOnly Property ISCOB() As String
            Get
                Return ResourceManager.GetString("ISCOB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Penjamin KLL?.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_ISLAKLANTAS() As String
            Get
                Return ResourceManager.GetString("JAMINAN_ISLAKLANTAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keterangan KLL.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_KETERANGAN() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_KETERANGAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jasa raharja PT.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_PENJAMIN1() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_PENJAMIN1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BPJS Ketenagakerjaan.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_PENJAMIN2() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_PENJAMIN2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TASPEN PT.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_PENJAMIN3() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_PENJAMIN3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ASABRI PT.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_PENJAMIN4() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_PENJAMIN4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suplesi?.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_SUPLESI_ISSUPLESI() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_SUPLESI_ISSUPLESI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Districts.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_SUPLESI_LOKASILAKA_KABUPATEN() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_SUPLESI_LOKASILAKA_KABUPATEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Province.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_SUPLESI_LOKASILAKA_KDPROPINSI() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_SUPLESI_LOKASILAKA_KDPROPINSI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub-district.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_SUPLESI_LOKASILAKA_KECAMATAN() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_SUPLESI_LOKASILAKA_KECAMATAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No SEP Suplesi.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_SUPLESI_NOSEPSUPLESI() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_SUPLESI_NOSEPSUPLESI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Occurrence.
        '''</summary>
        Public Shared ReadOnly Property JAMINAN_PENJAMIN_TGLKEJADIAN() As String
            Get
                Return ResourceManager.GetString("JAMINAN_PENJAMIN_TGLKEJADIAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. BPJS Card / Asuransi.
        '''</summary>
        Public Shared ReadOnly Property KARTUBPJS() As String
            Get
                Return ResourceManager.GetString("KARTUBPJS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COB.
        '''</summary>
        Public Shared ReadOnly Property KDCOB() As String
            Get
                Return ResourceManager.GetString("KDCOB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Medical Record.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_ALAMAT() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_ALAMAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDGOLONGAN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDGOLONGAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rank.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDPANGKAT() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDPANGKAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDPEKERJAAN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDPEKERJAAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Education.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDPENDIDIKAN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDPENDIDIKAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debtor.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDPENJAMIN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDPENJAMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDPERUSAHAAN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDPERUSAHAAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mating Status.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDSTATUSKAWIN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDSTATUSKAWIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Family Status.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KDSTATUSKELUARGA() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KDSTATUSKELUARGA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unity.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_KESATUAN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_KESATUAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER_NAMAPASIEN() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER_NAMAPASIEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poli / Ruangan.
        '''</summary>
        Public Shared ReadOnly Property KDDEPARTMENT() As String
            Get
                Return ResourceManager.GetString("KDDEPARTMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnosis.
        '''</summary>
        Public Shared ReadOnly Property KDDIAGNOSA() As String
            Get
                Return ResourceManager.GetString("KDDIAGNOSA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DPJP yg Melayani.
        '''</summary>
        Public Shared ReadOnly Property KDDOCTOR() As String
            Get
                Return ResourceManager.GetString("KDDOCTOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kelas Hak Rawat.
        '''</summary>
        Public Shared ReadOnly Property KDKELASRAWAT() As String
            Get
                Return ResourceManager.GetString("KDKELASRAWAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DPJP giver Letter SKDP/SPRI.
        '''</summary>
        Public Shared ReadOnly Property KDKONTROL() As String
            Get
                Return ResourceManager.GetString("KDKONTROL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration Number.
        '''</summary>
        Public Shared ReadOnly Property KDPENDAFTARAN() As String
            Get
                Return ResourceManager.GetString("KDPENDAFTARAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial Registration Number.
        '''</summary>
        Public Shared ReadOnly Property KDPENDAFTARAN_AWAL() As String
            Get
                Return ResourceManager.GetString("KDPENDAFTARAN_AWAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Faskes.
        '''</summary>
        Public Shared ReadOnly Property KDPPK() As String
            Get
                Return ResourceManager.GetString("KDPPK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accident Status.
        '''</summary>
        Public Shared ReadOnly Property KDSTATUSKECELAKAAN() As String
            Get
                Return ResourceManager.GetString("KDSTATUSKECELAKAAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. NIK.
        '''</summary>
        Public Shared ReadOnly Property KTP() As String
            Get
                Return ResourceManager.GetString("KTP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Reference.
        '''</summary>
        Public Shared ReadOnly Property NOMORRUJUKAN() As String
            Get
                Return ResourceManager.GetString("NOMORRUJUKAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. SEP.
        '''</summary>
        Public Shared ReadOnly Property NOMORSEP() As String
            Get
                Return ResourceManager.GetString("NOMORSEP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Control Letter/SKDP.
        '''</summary>
        Public Shared ReadOnly Property NOMORSKDP() As String
            Get
                Return ResourceManager.GetString("NOMORSKDP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Phone.
        '''</summary>
        Public Shared ReadOnly Property NOMORTELEPON() As String
            Get
                Return ResourceManager.GetString("NOMORTELEPON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status List.
        '''</summary>
        Public Shared ReadOnly Property STATUSDAFTAR() As String
            Get
                Return ResourceManager.GetString("STATUSDAFTAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information Patien.
        '''</summary>
        Public Shared ReadOnly Property TAB_1() As String
            Get
                Return ResourceManager.GetString("TAB_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The person in charge.
        '''</summary>
        Public Shared ReadOnly Property TAB_2() As String
            Get
                Return ResourceManager.GetString("TAB_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Potensi Suplesi Jasa Raharja.
        '''</summary>
        Public Shared ReadOnly Property TAB_3() As String
            Get
                Return ResourceManager.GetString("TAB_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Arrival.
        '''</summary>
        Public Shared ReadOnly Property TANGGAL() As String
            Get
                Return ResourceManager.GetString("TANGGAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration Report.
        '''</summary>
        Public Shared ReadOnly Property TITLE_REPORT() As String
            Get
                Return ResourceManager.GetString("TITLE_REPORT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
