'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Item
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.Item", GetType(Item).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount.
        '''</summary>
        Public Shared ReadOnly Property AMOUNT() As String
            Get
                Return ResourceManager.GetString("AMOUNT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount Sae.
        '''</summary>
        Public Shared ReadOnly Property AMOUNT_SAE() As String
            Get
                Return ResourceManager.GetString("AMOUNT_SAE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment.
        '''</summary>
        Public Shared ReadOnly Property ATTACHMENT() As String
            Get
                Return ResourceManager.GetString("ATTACHMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Public Shared ReadOnly Property CARD_DATE() As String
            Get
                Return ResourceManager.GetString("CARD_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price Average.
        '''</summary>
        Public Shared ReadOnly Property CARD_HPPAVERAGE() As String
            Get
                Return ResourceManager.GetString("CARD_HPPAVERAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price In.
        '''</summary>
        Public Shared ReadOnly Property CARD_HPPIN() As String
            Get
                Return ResourceManager.GetString("CARD_HPPIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price Out.
        '''</summary>
        Public Shared ReadOnly Property CARD_HPPOUT() As String
            Get
                Return ResourceManager.GetString("CARD_HPPOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference.
        '''</summary>
        Public Shared ReadOnly Property CARD_NOREFERENCE() As String
            Get
                Return ResourceManager.GetString("CARD_NOREFERENCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Average.
        '''</summary>
        Public Shared ReadOnly Property CARD_QTYAVERAGE() As String
            Get
                Return ResourceManager.GetString("CARD_QTYAVERAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty In.
        '''</summary>
        Public Shared ReadOnly Property CARD_QTYIN() As String
            Get
                Return ResourceManager.GetString("CARD_QTYIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Out.
        '''</summary>
        Public Shared ReadOnly Property CARD_QTYOUT() As String
            Get
                Return ResourceManager.GetString("CARD_QTYOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Average.
        '''</summary>
        Public Shared ReadOnly Property CARD_TOTALAVERAGE() As String
            Get
                Return ResourceManager.GetString("CARD_TOTALAVERAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total In.
        '''</summary>
        Public Shared ReadOnly Property CARD_TOTALIN() As String
            Get
                Return ResourceManager.GetString("CARD_TOTALIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total Out.
        '''</summary>
        Public Shared ReadOnly Property CARD_TOTALOUT() As String
            Get
                Return ResourceManager.GetString("CARD_TOTALOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit of Goods.
        '''</summary>
        Public Shared ReadOnly Property DETAILUOM_KDUOM() As String
            Get
                Return ResourceManager.GetString("DETAILUOM_KDUOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keuntungan.
        '''</summary>
        Public Shared ReadOnly Property DETAILUOM_MARGIN() As String
            Get
                Return ResourceManager.GetString("DETAILUOM_MARGIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Price.
        '''</summary>
        Public Shared ReadOnly Property DETAILUOM_PRICEPURCHASESTANDARD() As String
            Get
                Return ResourceManager.GetString("DETAILUOM_PRICEPURCHASESTANDARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sales Price.
        '''</summary>
        Public Shared ReadOnly Property DETAILUOM_PRICESALESSTANDARD() As String
            Get
                Return ResourceManager.GetString("DETAILUOM_PRICESALESSTANDARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rate.
        '''</summary>
        Public Shared ReadOnly Property DETAILUOM_RATE() As String
            Get
                Return ResourceManager.GetString("DETAILUOM_RATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Active?.
        '''</summary>
        Public Shared ReadOnly Property ISACTIVE() As String
            Get
                Return ResourceManager.GetString("ISACTIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Tax?.
        '''</summary>
        Public Shared ReadOnly Property ISTAX() As String
            Get
                Return ResourceManager.GetString("ISTAX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost Account.
        '''</summary>
        Public Shared ReadOnly Property KDCOA_COST() As String
            Get
                Return ResourceManager.GetString("KDCOA_COST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Account.
        '''</summary>
        Public Shared ReadOnly Property KDCOA_INVENTORY() As String
            Get
                Return ResourceManager.GetString("KDCOA_INVENTORY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sales Account.
        '''</summary>
        Public Shared ReadOnly Property KDCOA_SALES() As String
            Get
                Return ResourceManager.GetString("KDCOA_SALES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit.
        '''</summary>
        Public Shared ReadOnly Property KDUOM() As String
            Get
                Return ResourceManager.GetString("KDUOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse.
        '''</summary>
        Public Shared ReadOnly Property KDWAREHOUSE() As String
            Get
                Return ResourceManager.GetString("KDWAREHOUSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memo.
        '''</summary>
        Public Shared ReadOnly Property MEMO() As String
            Get
                Return ResourceManager.GetString("MEMO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tariff Group.
        '''</summary>
        Public Shared ReadOnly Property NMITEM1_1() As String
            Get
                Return ResourceManager.GetString("NMITEM1_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generik.
        '''</summary>
        Public Shared ReadOnly Property NMITEM1_2() As String
            Get
                Return ResourceManager.GetString("NMITEM1_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tariff Name.
        '''</summary>
        Public Shared ReadOnly Property NMITEM2_1() As String
            Get
                Return ResourceManager.GetString("NMITEM2_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dagang.
        '''</summary>
        Public Shared ReadOnly Property NMITEM2_2() As String
            Get
                Return ResourceManager.GetString("NMITEM2_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Public Shared ReadOnly Property NMITEM3_1() As String
            Get
                Return ResourceManager.GetString("NMITEM3_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retriksi.
        '''</summary>
        Public Shared ReadOnly Property NMITEM3_2() As String
            Get
                Return ResourceManager.GetString("NMITEM3_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price.
        '''</summary>
        Public Shared ReadOnly Property PRICE() As String
            Get
                Return ResourceManager.GetString("PRICE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum Quantity.
        '''</summary>
        Public Shared ReadOnly Property QTYMAXIMUM() As String
            Get
                Return ResourceManager.GetString("QTYMAXIMUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimum Quantity.
        '''</summary>
        Public Shared ReadOnly Property QTYMINIMUM() As String
            Get
                Return ResourceManager.GetString("QTYMINIMUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_ACCOUNT() As String
            Get
                Return ResourceManager.GetString("TAB_ACCOUNT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attachment Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_ATTACHMENT() As String
            Get
                Return ResourceManager.GetString("TAB_ATTACHMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service Item Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_JASA() As String
            Get
                Return ResourceManager.GetString("TAB_JASA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_SATUAN() As String
            Get
                Return ResourceManager.GetString("TAB_SATUAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spesification Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_SPESIFICATION() As String
            Get
                Return ResourceManager.GetString("TAB_SPESIFICATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rates.
        '''</summary>
        Public Shared ReadOnly Property TITLE_1() As String
            Get
                Return ResourceManager.GetString("TITLE_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drug.
        '''</summary>
        Public Shared ReadOnly Property TITLE_2() As String
            Get
                Return ResourceManager.GetString("TITLE_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monitoring Item.
        '''</summary>
        Public Shared ReadOnly Property TITLE_REPORT() As String
            Get
                Return ResourceManager.GetString("TITLE_REPORT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
