'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Staff
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.Staff", GetType(Staff).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agama.
        '''</summary>
        Public Shared ReadOnly Property AGAMA() As String
            Get
                Return ResourceManager.GetString("AGAMA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gambar.
        '''</summary>
        Public Shared ReadOnly Property ATTACMENT() As String
            Get
                Return ResourceManager.GetString("ATTACMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deskripsi.
        '''</summary>
        Public Shared ReadOnly Property DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Public Shared ReadOnly Property EMAIL() As String
            Get
                Return ResourceManager.GetString("EMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktif?.
        '''</summary>
        Public Shared ReadOnly Property ISACTIVE() As String
            Get
                Return ResourceManager.GetString("ISACTIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jenis Kelamin.
        '''</summary>
        Public Shared ReadOnly Property JENISKELAMIN() As String
            Get
                Return ResourceManager.GetString("JENISKELAMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kode.
        '''</summary>
        Public Shared ReadOnly Property KDSTAFF() As String
            Get
                Return ResourceManager.GetString("KDSTAFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bagian.
        '''</summary>
        Public Shared ReadOnly Property KDSTAFFBAGIAN() As String
            Get
                Return ResourceManager.GetString("KDSTAFFBAGIAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jabatan.
        '''</summary>
        Public Shared ReadOnly Property KDSTAFFJABATAN() As String
            Get
                Return ResourceManager.GetString("KDSTAFFJABATAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pangkat.
        '''</summary>
        Public Shared ReadOnly Property KDSTAFFPANGKAT() As String
            Get
                Return ResourceManager.GetString("KDSTAFFPANGKAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pendidikan.
        '''</summary>
        Public Shared ReadOnly Property KDSTAFFPENDIDIKAN() As String
            Get
                Return ResourceManager.GetString("KDSTAFFPENDIDIKAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nama.
        '''</summary>
        Public Shared ReadOnly Property NAME_DISPLAY() As String
            Get
                Return ResourceManager.GetString("NAME_DISPLAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. KTP.
        '''</summary>
        Public Shared ReadOnly Property NMOR_KTP() As String
            Get
                Return ResourceManager.GetString("NMOR_KTP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. HP 1.
        '''</summary>
        Public Shared ReadOnly Property NOMOR_HP1() As String
            Get
                Return ResourceManager.GetString("NOMOR_HP1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. HP 2.
        '''</summary>
        Public Shared ReadOnly Property NOMOR_HP2() As String
            Get
                Return ResourceManager.GetString("NOMOR_HP2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. NIP.
        '''</summary>
        Public Shared ReadOnly Property NOMOR_NIP() As String
            Get
                Return ResourceManager.GetString("NOMOR_NIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Public Shared ReadOnly Property STATUS() As String
            Get
                Return ResourceManager.GetString("STATUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tanggal Lahir.
        '''</summary>
        Public Shared ReadOnly Property TANGGALLAHIR() As String
            Get
                Return ResourceManager.GetString("TANGGALLAHIR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tempat Lahir.
        '''</summary>
        Public Shared ReadOnly Property TEMPATLAHIR() As String
            Get
                Return ResourceManager.GetString("TEMPATLAHIR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anggota.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TMT.
        '''</summary>
        Public Shared ReadOnly Property TMT() As String
            Get
                Return ResourceManager.GetString("TMT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
