'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class JadwalDokter
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.JadwalDokter", GetType(JadwalDokter).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catatan.
        '''</summary>
        Public Shared ReadOnly Property DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buka.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_BUKA() As String
            Get
                Return ResourceManager.GetString("DETAIL_BUKA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deskripsi.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_DESCRIPTION() As String
            Get
                Return ResourceManager.GetString("DETAIL_DESCRIPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hari.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_HARI() As String
            Get
                Return ResourceManager.GetString("DETAIL_HARI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kapasitas Pasien.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_KAPASITASPASIEN() As String
            Get
                Return ResourceManager.GetString("DETAIL_KAPASITASPASIEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Libur.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_LIBUR() As String
            Get
                Return ResourceManager.GetString("DETAIL_LIBUR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tutup.
        '''</summary>
        Public Shared ReadOnly Property DETAIL_TUTUP() As String
            Get
                Return ResourceManager.GetString("DETAIL_TUTUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub Spesialis.
        '''</summary>
        Public Shared ReadOnly Property KDDEPARTMENT() As String
            Get
                Return ResourceManager.GetString("KDDEPARTMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dokter.
        '''</summary>
        Public Shared ReadOnly Property KDDOCTOR() As String
            Get
                Return ResourceManager.GetString("KDDOCTOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nomor.
        '''</summary>
        Public Shared ReadOnly Property KDJADWALDOKTER() As String
            Get
                Return ResourceManager.GetString("KDJADWALDOKTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jadwa Dokter.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Laporan Jadwal Dokter.
        '''</summary>
        Public Shared ReadOnly Property TITLE_REPORT() As String
            Get
                Return ResourceManager.GetString("TITLE_REPORT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
