'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class RuangRawat
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.RuangRawat", GetType(RuangRawat).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Public Shared ReadOnly Property BILL_CITY() As String
            Get
                Return ResourceManager.GetString("BILL_CITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country.
        '''</summary>
        Public Shared ReadOnly Property BILL_COUNTRY() As String
            Get
                Return ResourceManager.GetString("BILL_COUNTRY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Public Shared ReadOnly Property BILL_STATE() As String
            Get
                Return ResourceManager.GetString("BILL_STATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Street.
        '''</summary>
        Public Shared ReadOnly Property BILL_STREET() As String
            Get
                Return ResourceManager.GetString("BILL_STREET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip Code.
        '''</summary>
        Public Shared ReadOnly Property BILL_ZIP() As String
            Get
                Return ResourceManager.GetString("BILL_ZIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Due.
        '''</summary>
        Public Shared ReadOnly Property DUE() As String
            Get
                Return ResourceManager.GetString("DUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Public Shared ReadOnly Property EMAIL() As String
            Get
                Return ResourceManager.GetString("EMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fax.
        '''</summary>
        Public Shared ReadOnly Property FAX() As String
            Get
                Return ResourceManager.GetString("FAX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Active?.
        '''</summary>
        Public Shared ReadOnly Property ISACTIVE() As String
            Get
                Return ResourceManager.GetString("ISACTIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Public Shared ReadOnly Property KDRUANGRAWAT() As String
            Get
                Return ResourceManager.GetString("KDRUANGRAWAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kode BPJS.
        '''</summary>
        Public Shared ReadOnly Property KDRUANGRAWAT_BPJS() As String
            Get
                Return ResourceManager.GetString("KDRUANGRAWAT_BPJS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memo.
        '''</summary>
        Public Shared ReadOnly Property MEMO() As String
            Get
                Return ResourceManager.GetString("MEMO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile.
        '''</summary>
        Public Shared ReadOnly Property MOBILE() As String
            Get
                Return ResourceManager.GetString("MOBILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display Name.
        '''</summary>
        Public Shared ReadOnly Property NAME_DISPLAY() As String
            Get
                Return ResourceManager.GetString("NAME_DISPLAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other.
        '''</summary>
        Public Shared ReadOnly Property OTHER() As String
            Get
                Return ResourceManager.GetString("OTHER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone.
        '''</summary>
        Public Shared ReadOnly Property PHONE() As String
            Get
                Return ResourceManager.GetString("PHONE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_BILL() As String
            Get
                Return ResourceManager.GetString("TAB_BILL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_CONTACT() As String
            Get
                Return ResourceManager.GetString("TAB_CONTACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Information.
        '''</summary>
        Public Shared ReadOnly Property TAB_OTHER() As String
            Get
                Return ResourceManager.GetString("TAB_OTHER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Room.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Website.
        '''</summary>
        Public Shared ReadOnly Property WEBSITE() As String
            Get
                Return ResourceManager.GetString("WEBSITE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
