'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="USER")>  _
Partial Public Class DataUserDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertSET_COMPANY(instance As SET_COMPANY)
    End Sub
  Partial Private Sub UpdateSET_COMPANY(instance As SET_COMPANY)
    End Sub
  Partial Private Sub DeleteSET_COMPANY(instance As SET_COMPANY)
    End Sub
  Partial Private Sub InsertSET_USER(instance As SET_USER)
    End Sub
  Partial Private Sub UpdateSET_USER(instance As SET_USER)
    End Sub
  Partial Private Sub DeleteSET_USER(instance As SET_USER)
    End Sub
  Partial Private Sub InsertSET_OTORITY_D(instance As SET_OTORITY_D)
    End Sub
  Partial Private Sub UpdateSET_OTORITY_D(instance As SET_OTORITY_D)
    End Sub
  Partial Private Sub DeleteSET_OTORITY_D(instance As SET_OTORITY_D)
    End Sub
  Partial Private Sub InsertSET_OTORITY_H(instance As SET_OTORITY_H)
    End Sub
  Partial Private Sub UpdateSET_OTORITY_H(instance As SET_OTORITY_H)
    End Sub
  Partial Private Sub DeleteSET_OTORITY_H(instance As SET_OTORITY_H)
    End Sub
  Partial Private Sub InsertSET_IMAGE(instance As SET_IMAGE)
    End Sub
  Partial Private Sub UpdateSET_IMAGE(instance As SET_IMAGE)
    End Sub
  Partial Private Sub DeleteSET_IMAGE(instance As SET_IMAGE)
    End Sub
  Partial Private Sub InsertSET_USER_FINGER(instance As SET_USER_FINGER)
    End Sub
  Partial Private Sub UpdateSET_USER_FINGER(instance As SET_USER_FINGER)
    End Sub
  Partial Private Sub DeleteSET_USER_FINGER(instance As SET_USER_FINGER)
    End Sub
  Partial Private Sub InsertSET_BPJS_KONEKSI(instance As SET_BPJS_KONEKSI)
    End Sub
  Partial Private Sub UpdateSET_BPJS_KONEKSI(instance As SET_BPJS_KONEKSI)
    End Sub
  Partial Private Sub DeleteSET_BPJS_KONEKSI(instance As SET_BPJS_KONEKSI)
    End Sub
  Partial Private Sub InsertSET_SATUSEHAT_KONEKSI(instance As SET_SATUSEHAT_KONEKSI)
    End Sub
  Partial Private Sub UpdateSET_SATUSEHAT_KONEKSI(instance As SET_SATUSEHAT_KONEKSI)
    End Sub
  Partial Private Sub DeleteSET_SATUSEHAT_KONEKSI(instance As SET_SATUSEHAT_KONEKSI)
    End Sub
  Partial Private Sub InsertSET_SATUSEHAT_KONEKSI_TOKEN(instance As SET_SATUSEHAT_KONEKSI_TOKEN)
    End Sub
  Partial Private Sub UpdateSET_SATUSEHAT_KONEKSI_TOKEN(instance As SET_SATUSEHAT_KONEKSI_TOKEN)
    End Sub
  Partial Private Sub DeleteSET_SATUSEHAT_KONEKSI_TOKEN(instance As SET_SATUSEHAT_KONEKSI_TOKEN)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.DataAccess.My.MySettings.Default.USERConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SET_COMPANies() As System.Data.Linq.Table(Of SET_COMPANY)
		Get
			Return Me.GetTable(Of SET_COMPANY)
		End Get
	End Property
	
	Public ReadOnly Property SET_USERs() As System.Data.Linq.Table(Of SET_USER)
		Get
			Return Me.GetTable(Of SET_USER)
		End Get
	End Property
	
	Public ReadOnly Property SET_OTORITY_Ds() As System.Data.Linq.Table(Of SET_OTORITY_D)
		Get
			Return Me.GetTable(Of SET_OTORITY_D)
		End Get
	End Property
	
	Public ReadOnly Property SET_OTORITY_Hs() As System.Data.Linq.Table(Of SET_OTORITY_H)
		Get
			Return Me.GetTable(Of SET_OTORITY_H)
		End Get
	End Property
	
	Public ReadOnly Property SET_IMAGEs() As System.Data.Linq.Table(Of SET_IMAGE)
		Get
			Return Me.GetTable(Of SET_IMAGE)
		End Get
	End Property
	
	Public ReadOnly Property SET_USER_FINGERs() As System.Data.Linq.Table(Of SET_USER_FINGER)
		Get
			Return Me.GetTable(Of SET_USER_FINGER)
		End Get
	End Property
	
	Public ReadOnly Property SET_BPJS_KONEKSIs() As System.Data.Linq.Table(Of SET_BPJS_KONEKSI)
		Get
			Return Me.GetTable(Of SET_BPJS_KONEKSI)
		End Get
	End Property
	
	Public ReadOnly Property SET_SATUSEHAT_KONEKSIs() As System.Data.Linq.Table(Of SET_SATUSEHAT_KONEKSI)
		Get
			Return Me.GetTable(Of SET_SATUSEHAT_KONEKSI)
		End Get
	End Property
	
	Public ReadOnly Property SET_SATUSEHAT_KONEKSI_TOKENs() As System.Data.Linq.Table(Of SET_SATUSEHAT_KONEKSI_TOKEN)
		Get
			Return Me.GetTable(Of SET_SATUSEHAT_KONEKSI_TOKEN)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_COMPANY")>  _
Partial Public Class SET_COMPANY
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDCOMPANY As String
	
	Private _COMPANY As String
	
	Private _ADDRESS As String
	
	Private _PHONE As String
	
	Private _NPWP As String
	
	Private _ISACTIVE As Boolean
	
	Private _SET_USERs As EntitySet(Of SET_USER)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDCOMPANYChanging(value As String)
    End Sub
    Partial Private Sub OnKDCOMPANYChanged()
    End Sub
    Partial Private Sub OnCOMPANYChanging(value As String)
    End Sub
    Partial Private Sub OnCOMPANYChanged()
    End Sub
    Partial Private Sub OnADDRESSChanging(value As String)
    End Sub
    Partial Private Sub OnADDRESSChanged()
    End Sub
    Partial Private Sub OnPHONEChanging(value As String)
    End Sub
    Partial Private Sub OnPHONEChanged()
    End Sub
    Partial Private Sub OnNPWPChanging(value As String)
    End Sub
    Partial Private Sub OnNPWPChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_USERs = New EntitySet(Of SET_USER)(AddressOf Me.attach_SET_USERs, AddressOf Me.detach_SET_USERs)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDCOMPANY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDCOMPANY() As String
		Get
			Return Me._KDCOMPANY
		End Get
		Set
			If (String.Equals(Me._KDCOMPANY, value) = false) Then
				Me.OnKDCOMPANYChanging(value)
				Me.SendPropertyChanging
				Me._KDCOMPANY = value
				Me.SendPropertyChanged("KDCOMPANY")
				Me.OnKDCOMPANYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property COMPANY() As String
		Get
			Return Me._COMPANY
		End Get
		Set
			If (String.Equals(Me._COMPANY, value) = false) Then
				Me.OnCOMPANYChanging(value)
				Me.SendPropertyChanging
				Me._COMPANY = value
				Me.SendPropertyChanged("COMPANY")
				Me.OnCOMPANYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ADDRESS", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property ADDRESS() As String
		Get
			Return Me._ADDRESS
		End Get
		Set
			If (String.Equals(Me._ADDRESS, value) = false) Then
				Me.OnADDRESSChanging(value)
				Me.SendPropertyChanging
				Me._ADDRESS = value
				Me.SendPropertyChanged("ADDRESS")
				Me.OnADDRESSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PHONE", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property PHONE() As String
		Get
			Return Me._PHONE
		End Get
		Set
			If (String.Equals(Me._PHONE, value) = false) Then
				Me.OnPHONEChanging(value)
				Me.SendPropertyChanging
				Me._PHONE = value
				Me.SendPropertyChanged("PHONE")
				Me.OnPHONEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NPWP", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property NPWP() As String
		Get
			Return Me._NPWP
		End Get
		Set
			If (String.Equals(Me._NPWP, value) = false) Then
				Me.OnNPWPChanging(value)
				Me.SendPropertyChanging
				Me._NPWP = value
				Me.SendPropertyChanged("NPWP")
				Me.OnNPWPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_COMPANY_SET_USER", Storage:="_SET_USERs", ThisKey:="KDCOMPANY", OtherKey:="KDCOMPANY")>  _
	Public Property SET_USERs() As EntitySet(Of SET_USER)
		Get
			Return Me._SET_USERs
		End Get
		Set
			Me._SET_USERs.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_COMPANY = Me
	End Sub
	
	Private Sub detach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_COMPANY = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_USER")>  _
Partial Public Class SET_USER
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDUSER As String
	
	Private _KDSERVER As String
	
	Private _KDDATABASE As String
	
	Private _KDSERVER_TAX As String
	
	Private _KDDATABASE_TAX As String
	
	Private _KDOTORITY As String
	
	Private _KDCOMPANY As String
	
	Private _PASSWORD As String
	
	Private _ISACTIVE As Boolean
	
	Private _NIK As String
	
	Private _KDDOCTOR As String
	
	Private _SKINDEFAULT As String
	
	Private _KDDATABASE_NEW As String
	
	Private _KDSERVER_NEW As String
	
	Private _SET_COMPANY As EntityRef(Of SET_COMPANY)
	
	Private _SET_OTORITY_H As EntityRef(Of SET_OTORITY_H)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDUSERChanging(value As String)
    End Sub
    Partial Private Sub OnKDUSERChanged()
    End Sub
    Partial Private Sub OnKDSERVERChanging(value As String)
    End Sub
    Partial Private Sub OnKDSERVERChanged()
    End Sub
    Partial Private Sub OnKDDATABASEChanging(value As String)
    End Sub
    Partial Private Sub OnKDDATABASEChanged()
    End Sub
    Partial Private Sub OnKDSERVER_TAXChanging(value As String)
    End Sub
    Partial Private Sub OnKDSERVER_TAXChanged()
    End Sub
    Partial Private Sub OnKDDATABASE_TAXChanging(value As String)
    End Sub
    Partial Private Sub OnKDDATABASE_TAXChanged()
    End Sub
    Partial Private Sub OnKDOTORITYChanging(value As String)
    End Sub
    Partial Private Sub OnKDOTORITYChanged()
    End Sub
    Partial Private Sub OnKDCOMPANYChanging(value As String)
    End Sub
    Partial Private Sub OnKDCOMPANYChanged()
    End Sub
    Partial Private Sub OnPASSWORDChanging(value As String)
    End Sub
    Partial Private Sub OnPASSWORDChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    Partial Private Sub OnNIKChanging(value As String)
    End Sub
    Partial Private Sub OnNIKChanged()
    End Sub
    Partial Private Sub OnKDDOCTORChanging(value As String)
    End Sub
    Partial Private Sub OnKDDOCTORChanged()
    End Sub
    Partial Private Sub OnSKINDEFAULTChanging(value As String)
    End Sub
    Partial Private Sub OnSKINDEFAULTChanged()
    End Sub
    Partial Private Sub OnKDDATABASE_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnKDDATABASE_NEWChanged()
    End Sub
    Partial Private Sub OnKDSERVER_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnKDSERVER_NEWChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_COMPANY = CType(Nothing, EntityRef(Of SET_COMPANY))
		Me._SET_OTORITY_H = CType(Nothing, EntityRef(Of SET_OTORITY_H))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDUSER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDUSER() As String
		Get
			Return Me._KDUSER
		End Get
		Set
			If (String.Equals(Me._KDUSER, value) = false) Then
				Me.OnKDUSERChanging(value)
				Me.SendPropertyChanging
				Me._KDUSER = value
				Me.SendPropertyChanged("KDUSER")
				Me.OnKDUSERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDSERVER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDSERVER() As String
		Get
			Return Me._KDSERVER
		End Get
		Set
			If (String.Equals(Me._KDSERVER, value) = false) Then
				Me.OnKDSERVERChanging(value)
				Me.SendPropertyChanging
				Me._KDSERVER = value
				Me.SendPropertyChanged("KDSERVER")
				Me.OnKDSERVERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDDATABASE", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDDATABASE() As String
		Get
			Return Me._KDDATABASE
		End Get
		Set
			If (String.Equals(Me._KDDATABASE, value) = false) Then
				Me.OnKDDATABASEChanging(value)
				Me.SendPropertyChanging
				Me._KDDATABASE = value
				Me.SendPropertyChanged("KDDATABASE")
				Me.OnKDDATABASEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDSERVER_TAX", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDSERVER_TAX() As String
		Get
			Return Me._KDSERVER_TAX
		End Get
		Set
			If (String.Equals(Me._KDSERVER_TAX, value) = false) Then
				Me.OnKDSERVER_TAXChanging(value)
				Me.SendPropertyChanging
				Me._KDSERVER_TAX = value
				Me.SendPropertyChanged("KDSERVER_TAX")
				Me.OnKDSERVER_TAXChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDDATABASE_TAX", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDDATABASE_TAX() As String
		Get
			Return Me._KDDATABASE_TAX
		End Get
		Set
			If (String.Equals(Me._KDDATABASE_TAX, value) = false) Then
				Me.OnKDDATABASE_TAXChanging(value)
				Me.SendPropertyChanging
				Me._KDDATABASE_TAX = value
				Me.SendPropertyChanged("KDDATABASE_TAX")
				Me.OnKDDATABASE_TAXChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDOTORITY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDOTORITY() As String
		Get
			Return Me._KDOTORITY
		End Get
		Set
			If (String.Equals(Me._KDOTORITY, value) = false) Then
				If Me._SET_OTORITY_H.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDOTORITYChanging(value)
				Me.SendPropertyChanging
				Me._KDOTORITY = value
				Me.SendPropertyChanged("KDOTORITY")
				Me.OnKDOTORITYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDCOMPANY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDCOMPANY() As String
		Get
			Return Me._KDCOMPANY
		End Get
		Set
			If (String.Equals(Me._KDCOMPANY, value) = false) Then
				If Me._SET_COMPANY.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDCOMPANYChanging(value)
				Me.SendPropertyChanging
				Me._KDCOMPANY = value
				Me.SendPropertyChanged("KDCOMPANY")
				Me.OnKDCOMPANYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PASSWORD", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property PASSWORD() As String
		Get
			Return Me._PASSWORD
		End Get
		Set
			If (String.Equals(Me._PASSWORD, value) = false) Then
				Me.OnPASSWORDChanging(value)
				Me.SendPropertyChanging
				Me._PASSWORD = value
				Me.SendPropertyChanged("PASSWORD")
				Me.OnPASSWORDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NIK", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property NIK() As String
		Get
			Return Me._NIK
		End Get
		Set
			If (String.Equals(Me._NIK, value) = false) Then
				Me.OnNIKChanging(value)
				Me.SendPropertyChanging
				Me._NIK = value
				Me.SendPropertyChanged("NIK")
				Me.OnNIKChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDDOCTOR", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDDOCTOR() As String
		Get
			Return Me._KDDOCTOR
		End Get
		Set
			If (String.Equals(Me._KDDOCTOR, value) = false) Then
				Me.OnKDDOCTORChanging(value)
				Me.SendPropertyChanging
				Me._KDDOCTOR = value
				Me.SendPropertyChanged("KDDOCTOR")
				Me.OnKDDOCTORChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SKINDEFAULT", DbType:="NVarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property SKINDEFAULT() As String
		Get
			Return Me._SKINDEFAULT
		End Get
		Set
			If (String.Equals(Me._SKINDEFAULT, value) = false) Then
				Me.OnSKINDEFAULTChanging(value)
				Me.SendPropertyChanging
				Me._SKINDEFAULT = value
				Me.SendPropertyChanged("SKINDEFAULT")
				Me.OnSKINDEFAULTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDDATABASE_NEW", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDDATABASE_NEW() As String
		Get
			Return Me._KDDATABASE_NEW
		End Get
		Set
			If (String.Equals(Me._KDDATABASE_NEW, value) = false) Then
				Me.OnKDDATABASE_NEWChanging(value)
				Me.SendPropertyChanging
				Me._KDDATABASE_NEW = value
				Me.SendPropertyChanged("KDDATABASE_NEW")
				Me.OnKDDATABASE_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDSERVER_NEW", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDSERVER_NEW() As String
		Get
			Return Me._KDSERVER_NEW
		End Get
		Set
			If (String.Equals(Me._KDSERVER_NEW, value) = false) Then
				Me.OnKDSERVER_NEWChanging(value)
				Me.SendPropertyChanging
				Me._KDSERVER_NEW = value
				Me.SendPropertyChanged("KDSERVER_NEW")
				Me.OnKDSERVER_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_COMPANY_SET_USER", Storage:="_SET_COMPANY", ThisKey:="KDCOMPANY", OtherKey:="KDCOMPANY", IsForeignKey:=true)>  _
	Public Property SET_COMPANY() As SET_COMPANY
		Get
			Return Me._SET_COMPANY.Entity
		End Get
		Set
			Dim previousValue As SET_COMPANY = Me._SET_COMPANY.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_COMPANY.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_COMPANY.Entity = Nothing
					previousValue.SET_USERs.Remove(Me)
				End If
				Me._SET_COMPANY.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_USERs.Add(Me)
					Me._KDCOMPANY = value.KDCOMPANY
				Else
					Me._KDCOMPANY = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_COMPANY")
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_USER", Storage:="_SET_OTORITY_H", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY", IsForeignKey:=true)>  _
	Public Property SET_OTORITY_H() As SET_OTORITY_H
		Get
			Return Me._SET_OTORITY_H.Entity
		End Get
		Set
			Dim previousValue As SET_OTORITY_H = Me._SET_OTORITY_H.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_OTORITY_H.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_OTORITY_H.Entity = Nothing
					previousValue.SET_USERs.Remove(Me)
				End If
				Me._SET_OTORITY_H.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_USERs.Add(Me)
					Me._KDOTORITY = value.KDOTORITY
				Else
					Me._KDOTORITY = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_OTORITY_H")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_OTORITY_D")>  _
Partial Public Class SET_OTORITY_D
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDOTORITY As String
	
	Private _MODUL As String
	
	Private _MENUNAME As String
	
	Private _ISADD As Boolean
	
	Private _ISUPDATE As Boolean
	
	Private _ISDELETE As Boolean
	
	Private _ISPRINT As Boolean
	
	Private _ISVIEW As Boolean
	
	Private _SET_OTORITY_H As EntityRef(Of SET_OTORITY_H)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDOTORITYChanging(value As String)
    End Sub
    Partial Private Sub OnKDOTORITYChanged()
    End Sub
    Partial Private Sub OnMODULChanging(value As String)
    End Sub
    Partial Private Sub OnMODULChanged()
    End Sub
    Partial Private Sub OnMENUNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnMENUNAMEChanged()
    End Sub
    Partial Private Sub OnISADDChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISADDChanged()
    End Sub
    Partial Private Sub OnISUPDATEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISUPDATEChanged()
    End Sub
    Partial Private Sub OnISDELETEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISDELETEChanged()
    End Sub
    Partial Private Sub OnISPRINTChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISPRINTChanged()
    End Sub
    Partial Private Sub OnISVIEWChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISVIEWChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_OTORITY_H = CType(Nothing, EntityRef(Of SET_OTORITY_H))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDOTORITY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDOTORITY() As String
		Get
			Return Me._KDOTORITY
		End Get
		Set
			If (String.Equals(Me._KDOTORITY, value) = false) Then
				If Me._SET_OTORITY_H.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDOTORITYChanging(value)
				Me.SendPropertyChanging
				Me._KDOTORITY = value
				Me.SendPropertyChanged("KDOTORITY")
				Me.OnKDOTORITYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MODUL", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property MODUL() As String
		Get
			Return Me._MODUL
		End Get
		Set
			If (String.Equals(Me._MODUL, value) = false) Then
				Me.OnMODULChanging(value)
				Me.SendPropertyChanging
				Me._MODUL = value
				Me.SendPropertyChanged("MODUL")
				Me.OnMODULChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MENUNAME", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property MENUNAME() As String
		Get
			Return Me._MENUNAME
		End Get
		Set
			If (String.Equals(Me._MENUNAME, value) = false) Then
				Me.OnMENUNAMEChanging(value)
				Me.SendPropertyChanging
				Me._MENUNAME = value
				Me.SendPropertyChanged("MENUNAME")
				Me.OnMENUNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISADD", DbType:="Bit NOT NULL")>  _
	Public Property ISADD() As Boolean
		Get
			Return Me._ISADD
		End Get
		Set
			If ((Me._ISADD = value)  _
						= false) Then
				Me.OnISADDChanging(value)
				Me.SendPropertyChanging
				Me._ISADD = value
				Me.SendPropertyChanged("ISADD")
				Me.OnISADDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISUPDATE", DbType:="Bit NOT NULL")>  _
	Public Property ISUPDATE() As Boolean
		Get
			Return Me._ISUPDATE
		End Get
		Set
			If ((Me._ISUPDATE = value)  _
						= false) Then
				Me.OnISUPDATEChanging(value)
				Me.SendPropertyChanging
				Me._ISUPDATE = value
				Me.SendPropertyChanged("ISUPDATE")
				Me.OnISUPDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISDELETE", DbType:="Bit NOT NULL")>  _
	Public Property ISDELETE() As Boolean
		Get
			Return Me._ISDELETE
		End Get
		Set
			If ((Me._ISDELETE = value)  _
						= false) Then
				Me.OnISDELETEChanging(value)
				Me.SendPropertyChanging
				Me._ISDELETE = value
				Me.SendPropertyChanged("ISDELETE")
				Me.OnISDELETEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISPRINT", DbType:="Bit NOT NULL")>  _
	Public Property ISPRINT() As Boolean
		Get
			Return Me._ISPRINT
		End Get
		Set
			If ((Me._ISPRINT = value)  _
						= false) Then
				Me.OnISPRINTChanging(value)
				Me.SendPropertyChanging
				Me._ISPRINT = value
				Me.SendPropertyChanged("ISPRINT")
				Me.OnISPRINTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISVIEW", DbType:="Bit NOT NULL")>  _
	Public Property ISVIEW() As Boolean
		Get
			Return Me._ISVIEW
		End Get
		Set
			If ((Me._ISVIEW = value)  _
						= false) Then
				Me.OnISVIEWChanging(value)
				Me.SendPropertyChanging
				Me._ISVIEW = value
				Me.SendPropertyChanged("ISVIEW")
				Me.OnISVIEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_OTORITY_D", Storage:="_SET_OTORITY_H", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY", IsForeignKey:=true)>  _
	Public Property SET_OTORITY_H() As SET_OTORITY_H
		Get
			Return Me._SET_OTORITY_H.Entity
		End Get
		Set
			Dim previousValue As SET_OTORITY_H = Me._SET_OTORITY_H.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_OTORITY_H.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_OTORITY_H.Entity = Nothing
					previousValue.SET_OTORITY_Ds.Remove(Me)
				End If
				Me._SET_OTORITY_H.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_OTORITY_Ds.Add(Me)
					Me._KDOTORITY = value.KDOTORITY
				Else
					Me._KDOTORITY = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_OTORITY_H")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_OTORITY_H")>  _
Partial Public Class SET_OTORITY_H
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDOTORITY As String
	
	Private _DESCRIPTION As String
	
	Private _ISACTIVE As Boolean
	
	Private _SET_USERs As EntitySet(Of SET_USER)
	
	Private _SET_OTORITY_Ds As EntitySet(Of SET_OTORITY_D)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDOTORITYChanging(value As String)
    End Sub
    Partial Private Sub OnKDOTORITYChanged()
    End Sub
    Partial Private Sub OnDESCRIPTIONChanging(value As String)
    End Sub
    Partial Private Sub OnDESCRIPTIONChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_USERs = New EntitySet(Of SET_USER)(AddressOf Me.attach_SET_USERs, AddressOf Me.detach_SET_USERs)
		Me._SET_OTORITY_Ds = New EntitySet(Of SET_OTORITY_D)(AddressOf Me.attach_SET_OTORITY_Ds, AddressOf Me.detach_SET_OTORITY_Ds)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDOTORITY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDOTORITY() As String
		Get
			Return Me._KDOTORITY
		End Get
		Set
			If (String.Equals(Me._KDOTORITY, value) = false) Then
				Me.OnKDOTORITYChanging(value)
				Me.SendPropertyChanging
				Me._KDOTORITY = value
				Me.SendPropertyChanged("KDOTORITY")
				Me.OnKDOTORITYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DESCRIPTION", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property DESCRIPTION() As String
		Get
			Return Me._DESCRIPTION
		End Get
		Set
			If (String.Equals(Me._DESCRIPTION, value) = false) Then
				Me.OnDESCRIPTIONChanging(value)
				Me.SendPropertyChanging
				Me._DESCRIPTION = value
				Me.SendPropertyChanged("DESCRIPTION")
				Me.OnDESCRIPTIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_USER", Storage:="_SET_USERs", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY")>  _
	Public Property SET_USERs() As EntitySet(Of SET_USER)
		Get
			Return Me._SET_USERs
		End Get
		Set
			Me._SET_USERs.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_OTORITY_D", Storage:="_SET_OTORITY_Ds", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY")>  _
	Public Property SET_OTORITY_Ds() As EntitySet(Of SET_OTORITY_D)
		Get
			Return Me._SET_OTORITY_Ds
		End Get
		Set
			Me._SET_OTORITY_Ds.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Me
	End Sub
	
	Private Sub detach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Nothing
	End Sub
	
	Private Sub attach_SET_OTORITY_Ds(ByVal entity As SET_OTORITY_D)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Me
	End Sub
	
	Private Sub detach_SET_OTORITY_Ds(ByVal entity As SET_OTORITY_D)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_IMAGE")>  _
Partial Public Class SET_IMAGE
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDIMAGE As String
	
	Private _ALAMAT As String
	
	Private _GAMBAR As System.Data.Linq.Binary
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDIMAGEChanging(value As String)
    End Sub
    Partial Private Sub OnKDIMAGEChanged()
    End Sub
    Partial Private Sub OnALAMATChanging(value As String)
    End Sub
    Partial Private Sub OnALAMATChanged()
    End Sub
    Partial Private Sub OnGAMBARChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnGAMBARChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDIMAGE", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDIMAGE() As String
		Get
			Return Me._KDIMAGE
		End Get
		Set
			If (String.Equals(Me._KDIMAGE, value) = false) Then
				Me.OnKDIMAGEChanging(value)
				Me.SendPropertyChanging
				Me._KDIMAGE = value
				Me.SendPropertyChanged("KDIMAGE")
				Me.OnKDIMAGEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ALAMAT", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property ALAMAT() As String
		Get
			Return Me._ALAMAT
		End Get
		Set
			If (String.Equals(Me._ALAMAT, value) = false) Then
				Me.OnALAMATChanging(value)
				Me.SendPropertyChanging
				Me._ALAMAT = value
				Me.SendPropertyChanged("ALAMAT")
				Me.OnALAMATChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GAMBAR", DbType:="Image", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property GAMBAR() As System.Data.Linq.Binary
		Get
			Return Me._GAMBAR
		End Get
		Set
			If (Object.Equals(Me._GAMBAR, value) = false) Then
				Me.OnGAMBARChanging(value)
				Me.SendPropertyChanging
				Me._GAMBAR = value
				Me.SendPropertyChanged("GAMBAR")
				Me.OnGAMBARChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_USER_FINGER")>  _
Partial Public Class SET_USER_FINGER
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDUSER As String
	
	Private _USERNAME As String
	
	Private _PASSWORD As String
	
	Private _ALAMATSIMPAN As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDUSERChanging(value As String)
    End Sub
    Partial Private Sub OnKDUSERChanged()
    End Sub
    Partial Private Sub OnUSERNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnUSERNAMEChanged()
    End Sub
    Partial Private Sub OnPASSWORDChanging(value As String)
    End Sub
    Partial Private Sub OnPASSWORDChanged()
    End Sub
    Partial Private Sub OnALAMATSIMPANChanging(value As String)
    End Sub
    Partial Private Sub OnALAMATSIMPANChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDUSER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDUSER() As String
		Get
			Return Me._KDUSER
		End Get
		Set
			If (String.Equals(Me._KDUSER, value) = false) Then
				Me.OnKDUSERChanging(value)
				Me.SendPropertyChanging
				Me._KDUSER = value
				Me.SendPropertyChanged("KDUSER")
				Me.OnKDUSERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USERNAME", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property USERNAME() As String
		Get
			Return Me._USERNAME
		End Get
		Set
			If (String.Equals(Me._USERNAME, value) = false) Then
				Me.OnUSERNAMEChanging(value)
				Me.SendPropertyChanging
				Me._USERNAME = value
				Me.SendPropertyChanged("USERNAME")
				Me.OnUSERNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PASSWORD", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property PASSWORD() As String
		Get
			Return Me._PASSWORD
		End Get
		Set
			If (String.Equals(Me._PASSWORD, value) = false) Then
				Me.OnPASSWORDChanging(value)
				Me.SendPropertyChanging
				Me._PASSWORD = value
				Me.SendPropertyChanged("PASSWORD")
				Me.OnPASSWORDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ALAMATSIMPAN", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property ALAMATSIMPAN() As String
		Get
			Return Me._ALAMATSIMPAN
		End Get
		Set
			If (String.Equals(Me._ALAMATSIMPAN, value) = false) Then
				Me.OnALAMATSIMPANChanging(value)
				Me.SendPropertyChanging
				Me._ALAMATSIMPAN = value
				Me.SendPropertyChanged("ALAMATSIMPAN")
				Me.OnALAMATSIMPANChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_BPJS_KONEKSI")>  _
Partial Public Class SET_BPJS_KONEKSI
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _DATECREATED As Date
	
	Private _DATEUPDATED As Date
	
	Private _KDKONEKSI As String
	
	Private _NAME_DISPLAY As String
	
	Private _PPKPELAYANAN As String
	
	Private _CONSID As String
	
	Private _SECREATKEY As String
	
	Private _ALAMATWEB As String
	
	Private _REMARKS As String
	
	Private _ISACTIVE As Boolean
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnDATECREATEDChanging(value As Date)
    End Sub
    Partial Private Sub OnDATECREATEDChanged()
    End Sub
    Partial Private Sub OnDATEUPDATEDChanging(value As Date)
    End Sub
    Partial Private Sub OnDATEUPDATEDChanged()
    End Sub
    Partial Private Sub OnKDKONEKSIChanging(value As String)
    End Sub
    Partial Private Sub OnKDKONEKSIChanged()
    End Sub
    Partial Private Sub OnNAME_DISPLAYChanging(value As String)
    End Sub
    Partial Private Sub OnNAME_DISPLAYChanged()
    End Sub
    Partial Private Sub OnPPKPELAYANANChanging(value As String)
    End Sub
    Partial Private Sub OnPPKPELAYANANChanged()
    End Sub
    Partial Private Sub OnCONSIDChanging(value As String)
    End Sub
    Partial Private Sub OnCONSIDChanged()
    End Sub
    Partial Private Sub OnSECREATKEYChanging(value As String)
    End Sub
    Partial Private Sub OnSECREATKEYChanged()
    End Sub
    Partial Private Sub OnALAMATWEBChanging(value As String)
    End Sub
    Partial Private Sub OnALAMATWEBChanged()
    End Sub
    Partial Private Sub OnREMARKSChanging(value As String)
    End Sub
    Partial Private Sub OnREMARKSChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATECREATED", DbType:="SmallDateTime NOT NULL")>  _
	Public Property DATECREATED() As Date
		Get
			Return Me._DATECREATED
		End Get
		Set
			If ((Me._DATECREATED = value)  _
						= false) Then
				Me.OnDATECREATEDChanging(value)
				Me.SendPropertyChanging
				Me._DATECREATED = value
				Me.SendPropertyChanged("DATECREATED")
				Me.OnDATECREATEDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATEUPDATED", DbType:="SmallDateTime NOT NULL")>  _
	Public Property DATEUPDATED() As Date
		Get
			Return Me._DATEUPDATED
		End Get
		Set
			If ((Me._DATEUPDATED = value)  _
						= false) Then
				Me.OnDATEUPDATEDChanging(value)
				Me.SendPropertyChanging
				Me._DATEUPDATED = value
				Me.SendPropertyChanged("DATEUPDATED")
				Me.OnDATEUPDATEDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDKONEKSI", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDKONEKSI() As String
		Get
			Return Me._KDKONEKSI
		End Get
		Set
			If (String.Equals(Me._KDKONEKSI, value) = false) Then
				Me.OnKDKONEKSIChanging(value)
				Me.SendPropertyChanging
				Me._KDKONEKSI = value
				Me.SendPropertyChanged("KDKONEKSI")
				Me.OnKDKONEKSIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NAME_DISPLAY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NAME_DISPLAY() As String
		Get
			Return Me._NAME_DISPLAY
		End Get
		Set
			If (String.Equals(Me._NAME_DISPLAY, value) = false) Then
				Me.OnNAME_DISPLAYChanging(value)
				Me.SendPropertyChanging
				Me._NAME_DISPLAY = value
				Me.SendPropertyChanged("NAME_DISPLAY")
				Me.OnNAME_DISPLAYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PPKPELAYANAN", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PPKPELAYANAN() As String
		Get
			Return Me._PPKPELAYANAN
		End Get
		Set
			If (String.Equals(Me._PPKPELAYANAN, value) = false) Then
				Me.OnPPKPELAYANANChanging(value)
				Me.SendPropertyChanging
				Me._PPKPELAYANAN = value
				Me.SendPropertyChanged("PPKPELAYANAN")
				Me.OnPPKPELAYANANChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONSID", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property CONSID() As String
		Get
			Return Me._CONSID
		End Get
		Set
			If (String.Equals(Me._CONSID, value) = false) Then
				Me.OnCONSIDChanging(value)
				Me.SendPropertyChanging
				Me._CONSID = value
				Me.SendPropertyChanged("CONSID")
				Me.OnCONSIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SECREATKEY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SECREATKEY() As String
		Get
			Return Me._SECREATKEY
		End Get
		Set
			If (String.Equals(Me._SECREATKEY, value) = false) Then
				Me.OnSECREATKEYChanging(value)
				Me.SendPropertyChanging
				Me._SECREATKEY = value
				Me.SendPropertyChanged("SECREATKEY")
				Me.OnSECREATKEYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ALAMATWEB", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property ALAMATWEB() As String
		Get
			Return Me._ALAMATWEB
		End Get
		Set
			If (String.Equals(Me._ALAMATWEB, value) = false) Then
				Me.OnALAMATWEBChanging(value)
				Me.SendPropertyChanging
				Me._ALAMATWEB = value
				Me.SendPropertyChanged("ALAMATWEB")
				Me.OnALAMATWEBChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REMARKS", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property REMARKS() As String
		Get
			Return Me._REMARKS
		End Get
		Set
			If (String.Equals(Me._REMARKS, value) = false) Then
				Me.OnREMARKSChanging(value)
				Me.SendPropertyChanging
				Me._REMARKS = value
				Me.SendPropertyChanged("REMARKS")
				Me.OnREMARKSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_SATUSEHAT_KONEKSI")>  _
Partial Public Class SET_SATUSEHAT_KONEKSI
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDKONEKSI As String
	
	Private _ORGANIZATIONID As String
	
	Private _CLIENTID As String
	
	Private _CLIENTSECRET As String
	
	Private _MEMO As String
	
	Private _ISACTIVE As Boolean
	
	Private _SET_SATUSEHAT_KONEKSI_TOKENs As EntitySet(Of SET_SATUSEHAT_KONEKSI_TOKEN)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDKONEKSIChanging(value As String)
    End Sub
    Partial Private Sub OnKDKONEKSIChanged()
    End Sub
    Partial Private Sub OnORGANIZATIONIDChanging(value As String)
    End Sub
    Partial Private Sub OnORGANIZATIONIDChanged()
    End Sub
    Partial Private Sub OnCLIENTIDChanging(value As String)
    End Sub
    Partial Private Sub OnCLIENTIDChanged()
    End Sub
    Partial Private Sub OnCLIENTSECRETChanging(value As String)
    End Sub
    Partial Private Sub OnCLIENTSECRETChanged()
    End Sub
    Partial Private Sub OnMEMOChanging(value As String)
    End Sub
    Partial Private Sub OnMEMOChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_SATUSEHAT_KONEKSI_TOKENs = New EntitySet(Of SET_SATUSEHAT_KONEKSI_TOKEN)(AddressOf Me.attach_SET_SATUSEHAT_KONEKSI_TOKENs, AddressOf Me.detach_SET_SATUSEHAT_KONEKSI_TOKENs)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDKONEKSI", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDKONEKSI() As String
		Get
			Return Me._KDKONEKSI
		End Get
		Set
			If (String.Equals(Me._KDKONEKSI, value) = false) Then
				Me.OnKDKONEKSIChanging(value)
				Me.SendPropertyChanging
				Me._KDKONEKSI = value
				Me.SendPropertyChanged("KDKONEKSI")
				Me.OnKDKONEKSIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORGANIZATIONID", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property ORGANIZATIONID() As String
		Get
			Return Me._ORGANIZATIONID
		End Get
		Set
			If (String.Equals(Me._ORGANIZATIONID, value) = false) Then
				Me.OnORGANIZATIONIDChanging(value)
				Me.SendPropertyChanging
				Me._ORGANIZATIONID = value
				Me.SendPropertyChanged("ORGANIZATIONID")
				Me.OnORGANIZATIONIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTID", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property CLIENTID() As String
		Get
			Return Me._CLIENTID
		End Get
		Set
			If (String.Equals(Me._CLIENTID, value) = false) Then
				Me.OnCLIENTIDChanging(value)
				Me.SendPropertyChanging
				Me._CLIENTID = value
				Me.SendPropertyChanged("CLIENTID")
				Me.OnCLIENTIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CLIENTSECRET", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property CLIENTSECRET() As String
		Get
			Return Me._CLIENTSECRET
		End Get
		Set
			If (String.Equals(Me._CLIENTSECRET, value) = false) Then
				Me.OnCLIENTSECRETChanging(value)
				Me.SendPropertyChanging
				Me._CLIENTSECRET = value
				Me.SendPropertyChanged("CLIENTSECRET")
				Me.OnCLIENTSECRETChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MEMO", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property MEMO() As String
		Get
			Return Me._MEMO
		End Get
		Set
			If (String.Equals(Me._MEMO, value) = false) Then
				Me.OnMEMOChanging(value)
				Me.SendPropertyChanging
				Me._MEMO = value
				Me.SendPropertyChanged("MEMO")
				Me.OnMEMOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_SATUSEHAT_KONEKSI_SET_SATUSEHAT_KONEKSI_TOKEN", Storage:="_SET_SATUSEHAT_KONEKSI_TOKENs", ThisKey:="KDKONEKSI", OtherKey:="KDKONEKSI")>  _
	Public Property SET_SATUSEHAT_KONEKSI_TOKENs() As EntitySet(Of SET_SATUSEHAT_KONEKSI_TOKEN)
		Get
			Return Me._SET_SATUSEHAT_KONEKSI_TOKENs
		End Get
		Set
			Me._SET_SATUSEHAT_KONEKSI_TOKENs.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_SET_SATUSEHAT_KONEKSI_TOKENs(ByVal entity As SET_SATUSEHAT_KONEKSI_TOKEN)
		Me.SendPropertyChanging
		entity.SET_SATUSEHAT_KONEKSI = Me
	End Sub
	
	Private Sub detach_SET_SATUSEHAT_KONEKSI_TOKENs(ByVal entity As SET_SATUSEHAT_KONEKSI_TOKEN)
		Me.SendPropertyChanging
		entity.SET_SATUSEHAT_KONEKSI = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_SATUSEHAT_KONEKSI_TOKEN")>  _
Partial Public Class SET_SATUSEHAT_KONEKSI_TOKEN
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _DATECREATED As Date
	
	Private _DATEUPDATED As Date
	
	Private _KDKONEKSI As String
	
	Private _SEQ As Integer
	
	Private _COLLECTIONS As String
	
	Private _URL As String
	
	Private _GENERATETOKEN As String
	
	Private _MEMO As String
	
	Private _KDUSER As String
	
	Private _ISACTIVE As Boolean
	
	Private _SET_SATUSEHAT_KONEKSI As EntityRef(Of SET_SATUSEHAT_KONEKSI)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnDATECREATEDChanging(value As Date)
    End Sub
    Partial Private Sub OnDATECREATEDChanged()
    End Sub
    Partial Private Sub OnDATEUPDATEDChanging(value As Date)
    End Sub
    Partial Private Sub OnDATEUPDATEDChanged()
    End Sub
    Partial Private Sub OnKDKONEKSIChanging(value As String)
    End Sub
    Partial Private Sub OnKDKONEKSIChanged()
    End Sub
    Partial Private Sub OnSEQChanging(value As Integer)
    End Sub
    Partial Private Sub OnSEQChanged()
    End Sub
    Partial Private Sub OnCOLLECTIONSChanging(value As String)
    End Sub
    Partial Private Sub OnCOLLECTIONSChanged()
    End Sub
    Partial Private Sub OnURLChanging(value As String)
    End Sub
    Partial Private Sub OnURLChanged()
    End Sub
    Partial Private Sub OnGENERATETOKENChanging(value As String)
    End Sub
    Partial Private Sub OnGENERATETOKENChanged()
    End Sub
    Partial Private Sub OnMEMOChanging(value As String)
    End Sub
    Partial Private Sub OnMEMOChanged()
    End Sub
    Partial Private Sub OnKDUSERChanging(value As String)
    End Sub
    Partial Private Sub OnKDUSERChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_SATUSEHAT_KONEKSI = CType(Nothing, EntityRef(Of SET_SATUSEHAT_KONEKSI))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATECREATED", DbType:="SmallDateTime NOT NULL")>  _
	Public Property DATECREATED() As Date
		Get
			Return Me._DATECREATED
		End Get
		Set
			If ((Me._DATECREATED = value)  _
						= false) Then
				Me.OnDATECREATEDChanging(value)
				Me.SendPropertyChanging
				Me._DATECREATED = value
				Me.SendPropertyChanged("DATECREATED")
				Me.OnDATECREATEDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATEUPDATED", DbType:="SmallDateTime NOT NULL")>  _
	Public Property DATEUPDATED() As Date
		Get
			Return Me._DATEUPDATED
		End Get
		Set
			If ((Me._DATEUPDATED = value)  _
						= false) Then
				Me.OnDATEUPDATEDChanging(value)
				Me.SendPropertyChanging
				Me._DATEUPDATED = value
				Me.SendPropertyChanged("DATEUPDATED")
				Me.OnDATEUPDATEDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDKONEKSI", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDKONEKSI() As String
		Get
			Return Me._KDKONEKSI
		End Get
		Set
			If (String.Equals(Me._KDKONEKSI, value) = false) Then
				If Me._SET_SATUSEHAT_KONEKSI.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDKONEKSIChanging(value)
				Me.SendPropertyChanging
				Me._KDKONEKSI = value
				Me.SendPropertyChanged("KDKONEKSI")
				Me.OnKDKONEKSIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEQ", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property SEQ() As Integer
		Get
			Return Me._SEQ
		End Get
		Set
			If ((Me._SEQ = value)  _
						= false) Then
				Me.OnSEQChanging(value)
				Me.SendPropertyChanging
				Me._SEQ = value
				Me.SendPropertyChanged("SEQ")
				Me.OnSEQChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COLLECTIONS", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property COLLECTIONS() As String
		Get
			Return Me._COLLECTIONS
		End Get
		Set
			If (String.Equals(Me._COLLECTIONS, value) = false) Then
				Me.OnCOLLECTIONSChanging(value)
				Me.SendPropertyChanging
				Me._COLLECTIONS = value
				Me.SendPropertyChanged("COLLECTIONS")
				Me.OnCOLLECTIONSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_URL", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property URL() As String
		Get
			Return Me._URL
		End Get
		Set
			If (String.Equals(Me._URL, value) = false) Then
				Me.OnURLChanging(value)
				Me.SendPropertyChanging
				Me._URL = value
				Me.SendPropertyChanged("URL")
				Me.OnURLChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GENERATETOKEN", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property GENERATETOKEN() As String
		Get
			Return Me._GENERATETOKEN
		End Get
		Set
			If (String.Equals(Me._GENERATETOKEN, value) = false) Then
				Me.OnGENERATETOKENChanging(value)
				Me.SendPropertyChanging
				Me._GENERATETOKEN = value
				Me.SendPropertyChanged("GENERATETOKEN")
				Me.OnGENERATETOKENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MEMO", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property MEMO() As String
		Get
			Return Me._MEMO
		End Get
		Set
			If (String.Equals(Me._MEMO, value) = false) Then
				Me.OnMEMOChanging(value)
				Me.SendPropertyChanging
				Me._MEMO = value
				Me.SendPropertyChanged("MEMO")
				Me.OnMEMOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDUSER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDUSER() As String
		Get
			Return Me._KDUSER
		End Get
		Set
			If (String.Equals(Me._KDUSER, value) = false) Then
				Me.OnKDUSERChanging(value)
				Me.SendPropertyChanging
				Me._KDUSER = value
				Me.SendPropertyChanged("KDUSER")
				Me.OnKDUSERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_SATUSEHAT_KONEKSI_SET_SATUSEHAT_KONEKSI_TOKEN", Storage:="_SET_SATUSEHAT_KONEKSI", ThisKey:="KDKONEKSI", OtherKey:="KDKONEKSI", IsForeignKey:=true)>  _
	Public Property SET_SATUSEHAT_KONEKSI() As SET_SATUSEHAT_KONEKSI
		Get
			Return Me._SET_SATUSEHAT_KONEKSI.Entity
		End Get
		Set
			Dim previousValue As SET_SATUSEHAT_KONEKSI = Me._SET_SATUSEHAT_KONEKSI.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_SATUSEHAT_KONEKSI.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_SATUSEHAT_KONEKSI.Entity = Nothing
					previousValue.SET_SATUSEHAT_KONEKSI_TOKENs.Remove(Me)
				End If
				Me._SET_SATUSEHAT_KONEKSI.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_SATUSEHAT_KONEKSI_TOKENs.Add(Me)
					Me._KDKONEKSI = value.KDKONEKSI
				Else
					Me._KDKONEKSI = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_SATUSEHAT_KONEKSI")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
